# Generated by Django 5.2.7 on 2025-10-17 09:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.status')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.subcategory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.txtype')),
            ],
        ),
    ]
